### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by frankiecancino** [matrix-profile-foundation/mpf-org#14]
When reading a blog post, then trying to click the "Matrix Profile Foundation" button to go back to the home page, I get a 404 page not found error. Occurs in the Dev and Prod site.

**Comment by frankiecancino** [comment]
Thought this might be good to know since we are putting Andrew's blog post up soon.

**Comment by tylerwmarrs** [comment]
This is fixed and pushed to the dev site. Thanks for pointing it out.
